language: php
php:
  - '7.0'
dist: precise
services:
  - mysql
before_script:
  - mysql -uroot -e "create database test;"
  - mysql -uroot -e "use test; CREATE TABLE test ( id int(6) NOT NULL, sei varchar(256) NOT NULL, mei varchar(256) NOT NULL, yubin varchar(256) NOT NULL, tel varchar(256) NOT NULL, created_at timestamp NOT NULL DEFAULT 0, updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;"
  - composer self-update
  - composer install
script:
  - mkdir -p build/logs
  - chmod -R 777 build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - travis_retry php vendor/bin/php-coveralls -v